on:
  push:
    branches:
      - main
  pull_request:
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v2
        with:
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: test